# pyproject.toml
[tool.ruff]
line-length = 88  # Set the maximum line length (default is 88)
select = [
    "D", # Enable all pydocstyle (PEP 257) checks
    "E",
    "F",
    "W"
] # Enable specific linting rules (e.g., errors, warnings)
ignore = []  # Add specific rules to ignore
exclude = [
    "assas_database/",
    "doc/",
    "test/",
    "tools/",
    "flask_app/dash_app/pages/"
]  # Exclude specific directories
[tool.black]
line-length = 88  # Set the maximum line length (default is 88)
exclude = '''
/(
    assasdb/data/|  # Exclude the 'data' directory
    assasdb/tools/jobs/|  # Exclude the 'jobs' directory
)'''