# pyproject.toml
[tool.ruff]
line-length = 88
select = [
    "ANN",
    "D", # Enable all pydocstyle (PEP 257) checks
    "E",
    "F",
    "W"
]
ignore = []
exclude = [
    "assas_database/",
    "doc/",
    "test/",
    "tools/",
    "flask_app/auth/",
    "flask_app/dash_app/pages/database.py"
]
[tool.black]
line-length = 88
exclude = '''
/(
    assasdb/data/|
    assasdb/tools/jobs/|
)'''