name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"  # Match all branches
  pull_request:
    branches:
      - "**"  # Match all branches

jobs:
  
  lint:
    name: Run Ruff Linting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
        #with:
        #  submodules: recursive
      
      # Step 2
      - name: Debug Secrets
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c
      
      # Step 3: Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # Step 2: Build the Docker container
      - name: Build Docker container for Ruff
        run: |
          docker build -f Dockerfile.base \
            --build-arg SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}" \
            --build-arg GIT_BRANCH="${GITHUB_REF_NAME}" \
            -t assas-data-hub-ruff .

      # Step 3: Run Ruff linting inside the Docker container
      - name: Run Ruff
        run: |
          docker run --rm assas-data-hub-ruff \
            ruff check .
